import json
import platform

from openai import OpenAI

from .config import AgentConfig, PROJECT_ROOT

from tools.registry import ToolRegistry
from tools.schemas import TOOLS


# ============================================================
# Prompt loader
# ============================================================

def load_system_prompt() -> str:
    """
    Load the system prompt from:

    prompts/system_prompt.md
    """

    prompt_path = (
        PROJECT_ROOT
        / "prompts"
        / "system_prompt.md"
    )

    if not prompt_path.exists():
        raise FileNotFoundError(
            f"System prompt not found: {prompt_path}"
        )

    return prompt_path.read_text(
        encoding="utf-8"
    )


# ============================================================
# Coding Agent
# ============================================================

class CodingAgent:
    """
    Minimal autonomous coding agent.

    Responsibilities:

    1. Maintain conversation history.
    2. Call the LLM.
    3. Parse tool calls.
    4. Dispatch tools through ToolRegistry.
    5. Feed tool results back to the LLM.
    6. Decide when the agent is allowed to finish.
    """

    def __init__(
        self,
        workspace: str = "workspace",
        max_steps: int = 12,
        config: AgentConfig | None = None,
    ):
        # ----------------------------------------------------
        # Configuration
        # ----------------------------------------------------

        if config is None:
            config = AgentConfig.from_env(
                workspace=workspace,
                max_steps=max_steps,
            )

        self.config = config

        # ----------------------------------------------------
        # Qwen client
        # ----------------------------------------------------

        self.client = OpenAI(
            api_key=self.config.api_key,
            base_url=self.config.base_url,
        )

        # ----------------------------------------------------
        # Tool system
        # ----------------------------------------------------

        self.tool_registry = ToolRegistry(
            workspace=self.config.workspace,
        )

        # ----------------------------------------------------
        # Prompt
        # ----------------------------------------------------

        self.system_prompt = (
            load_system_prompt()
        )

    # ========================================================
    # Assistant message conversion
    # ========================================================

    def _assistant_message_to_dict(
        self,
        message,
    ) -> dict:
        """
        Convert the message returned by the OpenAI-compatible
        SDK into a plain dictionary.

        The conversation history is maintained locally by
        this agent rather than by the API service.
        """

        result = {
            "role": "assistant",
            "content": message.content or "",
        }

        if message.tool_calls:
            result["tool_calls"] = []

            for tool_call in message.tool_calls:
                result["tool_calls"].append(
                    {
                        "id": tool_call.id,
                        "type": "function",
                        "function": {
                            "name": (
                                tool_call.function.name
                            ),
                            "arguments": (
                                tool_call.function.arguments
                            ),
                        },
                    }
                )

        return result

    # ========================================================
    # Tool execution
    # ========================================================

    def _execute_tool(
        self,
        name: str,
        arguments: dict,
    ) -> str:
        """
        Execute a tool through ToolRegistry.
        """

        return self.tool_registry.execute(
            name=name,
            arguments=arguments,
        )

    # ========================================================
    # Runtime feedback
    # ========================================================

    @staticmethod
    def _append_runtime_feedback(
        messages: list,
        content: str,
    ) -> None:
        """
        Add feedback generated by the agent runtime itself
        back into the conversation.

        This is different from a tool result:
        it represents a constraint enforced by our agent.
        """

        messages.append(
            {
                "role": "user",
                "content": (
                    "[Agent runtime feedback]\n"
                    + content
                ),
            }
        )

    # ========================================================
    # Main Agent Loop
    # ========================================================

    def run(
        self,
        user_task: str,
    ) -> str:
        """
        Execute one coding task.

        Core loop:

        user task
            ↓
        LLM decision
            ↓
        tool call
            ↓
        local tool execution
            ↓
        observation
            ↓
        LLM decision
            ↓
        ...
            ↓
        final answer
        """

        current_os = platform.system()

        system_prompt = (
            self.system_prompt
            + "\n\n"
            + f"Current operating system: {current_os}"
        )

        # ----------------------------------------------------
        # Conversation history
        # ----------------------------------------------------

        messages = [
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_task,
            },
        ]

        # ----------------------------------------------------
        # Runtime state
        # ----------------------------------------------------

        # Number of successful source-code writes.
        #
        # Example:
        #
        # first generated version -> 1
        # fixed version           -> 2
        #
        write_version = 0

        # Which source-code version has successfully
        # passed runtime validation.
        validated_version = -1

        # ----------------------------------------------------
        # Agent Loop
        # ----------------------------------------------------

        for step in range(
            1,
            self.config.max_steps + 1,
        ):
            print()
            print(
                "========================================"
            )
            print(
                f"Agent Step "
                f"{step}/{self.config.max_steps}"
            )
            print(
                "========================================"
            )

            # =================================================
            # Ask Qwen what to do next
            # =================================================

            response = (
                self.client
                .chat
                .completions
                .create(
                    model=self.config.model,
                    messages=messages,
                    tools=TOOLS,
                    tool_choice="auto",
                )
            )

            assistant_message = (
                response
                .choices[0]
                .message
            )

            # Save assistant response into
            # our locally maintained history.
            messages.append(
                self._assistant_message_to_dict(
                    assistant_message
                )
            )

            tool_calls = (
                assistant_message.tool_calls
            )

            # =================================================
            # No tool call:
            # the LLM wants to finish
            # =================================================

            if not tool_calls:

                # ---------------------------------------------
                # Guard 1:
                # Source file must have been created
                # ---------------------------------------------

                if write_version == 0:
                    print(
                        "[Runtime Guard] "
                        "Model attempted to finish "
                        "without creating a source file."
                    )

                    self._append_runtime_feedback(
                        messages,
                        (
                            "You have not created the "
                            "requested source file yet. "
                            "Continue the task using tools."
                        ),
                    )

                    continue

                # ---------------------------------------------
                # Guard 2:
                # Latest version must have been run
                # ---------------------------------------------

                if (
                    validated_version
                    != write_version
                ):
                    print(
                        "[Runtime Guard] "
                        "Latest source version has not "
                        "passed runtime validation."
                    )

                    self._append_runtime_feedback(
                        messages,
                        (
                            "The latest source-code "
                            "version has not yet passed "
                            "successful runtime validation. "
                            "Continue using run_command."
                        ),
                    )

                    continue

                # ---------------------------------------------
                # Agent may finish
                # ---------------------------------------------

                return (
                    assistant_message.content
                    or "Task completed successfully."
                )

            # =================================================
            # Execute tool calls
            # =================================================

            for tool_call in tool_calls:

                tool_name = (
                    tool_call.function.name
                )

                print()
                print(
                    f"[Tool Call] {tool_name}"
                )

                # ---------------------------------------------
                # Parse tool arguments
                # ---------------------------------------------

                try:
                    arguments = json.loads(
                        tool_call
                        .function
                        .arguments
                    )

                except json.JSONDecodeError as e:
                    tool_result = json.dumps(
                        {
                            "ok": False,
                            "error": (
                                "Invalid JSON arguments "
                                "generated by the model: "
                                + str(e)
                            ),
                        },
                        ensure_ascii=False,
                    )

                    messages.append(
                        {
                            "role": "tool",
                            "tool_call_id": (
                                tool_call.id
                            ),
                            "content": tool_result,
                        }
                    )

                    continue

                print(
                    json.dumps(
                        arguments,
                        ensure_ascii=False,
                        indent=2,
                    )
                )

                # ---------------------------------------------
                # Execute tool locally
                # ---------------------------------------------

                try:
                    tool_result = (
                        self._execute_tool(
                            name=tool_name,
                            arguments=arguments,
                        )
                    )

                except Exception as e:
                    tool_result = json.dumps(
                        {
                            "ok": False,
                            "error": str(e),
                        },
                        ensure_ascii=False,
                    )

                print()
                print(
                    "[Tool Result]"
                )
                print(
                    tool_result
                )

                # ---------------------------------------------
                # Parse result for runtime state
                # ---------------------------------------------

                try:
                    result_data = json.loads(
                        tool_result
                    )

                except json.JSONDecodeError:
                    result_data = {
                        "ok": False,
                    }

                # ---------------------------------------------
                # Successful file write
                # ---------------------------------------------

                if (
                    tool_name == "write_file"
                    and result_data.get("ok")
                ):
                    write_version += 1

                # ---------------------------------------------
                # Successful runtime validation
                # ---------------------------------------------

                if (
                    tool_name == "run_command"
                    and result_data.get("ok")
                ):
                    purpose = arguments.get(
                        "purpose"
                    )

                    if purpose in {
                        "run",
                        "test",
                    }:
                        validated_version = (
                            write_version
                        )

                # ---------------------------------------------
                # Feed observation back to Qwen
                # ---------------------------------------------

                messages.append(
                    {
                        "role": "tool",
                        "tool_call_id": (
                            tool_call.id
                        ),
                        "content": tool_result,
                    }
                )

        # ====================================================
        # Maximum-step termination
        # ====================================================

        raise RuntimeError(
            "Agent reached the maximum number "
            f"of steps ({self.config.max_steps}) "
            "without completing the task."
        )