from copy import deepcopy


class ConversationHistory:
    """
    Maintain the complete local conversation history.

    This class stores what actually happened during one agent run.

    It does not decide which messages should be sent to the model.
    That responsibility belongs to ContextManager.
    """

    VALID_ROLES = {
        "system",
        "user",
        "assistant",
        "tool",
    }

    def __init__(self) -> None:
        self._messages: list[dict] = []

    # ========================================================
    # Conversation lifecycle
    # ========================================================

    def reset(
        self,
        system_prompt: str,
        user_task: str,
    ) -> None:
        """
        Start a new conversation.
        """

        self._messages = []

        self.add_system_message(
            system_prompt
        )

        self.add_user_message(
            user_task
        )

    # ========================================================
    # Add messages
    # ========================================================

    def add_system_message(
        self,
        content: str,
    ) -> None:
        self._append(
            {
                "role": "system",
                "content": content,
            }
        )

    def add_user_message(
        self,
        content: str,
    ) -> None:
        self._append(
            {
                "role": "user",
                "content": content,
            }
        )

    def add_assistant_message(
        self,
        message: dict,
    ) -> None:
        """
        Add a parsed assistant message.

        The message may contain tool_calls and therefore is accepted
        as a dictionary instead of only a content string.
        """

        if (
            message.get("role")
            != "assistant"
        ):
            raise ValueError(
                "Assistant message must have "
                "role='assistant'."
            )

        self._append(
            message
        )

    def add_tool_result(
        self,
        tool_call_id: str,
        content: str,
    ) -> None:
        self._append(
            {
                "role": "tool",
                "tool_call_id": (
                    tool_call_id
                ),
                "content": content,
            }
        )

    def add_runtime_feedback(
        self,
        content: str,
    ) -> None:
        """
        Add feedback generated by our own agent runtime.

        Example:

        The model wants to finish, but the latest source version
        has not been tested yet.
        """

        self.add_user_message(
            "[Agent runtime feedback]\n"
            + content
        )

    # ========================================================
    # Read history
    # ========================================================

    def get_messages(
        self,
    ) -> list[dict]:
        """
        Return a copy of the complete history.

        Returning a copy prevents external code from accidentally
        modifying the internal conversation state.
        """

        return deepcopy(
            self._messages
        )

    # ========================================================
    # Persistence support
    # ========================================================

    def restore(
        self,
        messages: list[dict],
    ) -> None:
        """
        Restore previously persisted messages.

        SessionStore can use this method later.
        """

        restored: list[dict] = []

        for message in messages:
            role = message.get(
                "role"
            )

            if role not in self.VALID_ROLES:
                raise ValueError(
                    f"Invalid message role: {role}"
                )

            restored.append(
                deepcopy(message)
            )

        self._messages = restored

    # ========================================================
    # Utility
    # ========================================================

    def clear(self) -> None:
        self._messages.clear()

    def __len__(self) -> int:
        return len(
            self._messages
        )

    def _append(
        self,
        message: dict,
    ) -> None:
        role = message.get(
            "role"
        )

        if role not in self.VALID_ROLES:
            raise ValueError(
                f"Invalid message role: {role}"
            )

        self._messages.append(
            deepcopy(message)
        )